version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user_mgmt:
    build: ./user_mgmt
    ports:
      - "5005:5005"
    environment:
      MONGO_URI: mongodb://mongodb:27017/NEUROCON
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5005/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  input_mgmt:
    build: ./input_mgmt
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/NEUROCON
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  model_mgmt:
    build: ./model_mgmt
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: mongodb://mongodb:27017/NEUROCON
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5002/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  output_mgmt:
    build: ./output_mgmt
    ports:
      - "5003:5003"
    environment:
      MONGO_URI: mongodb://mongodb:27017/NEUROCON
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5003/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo_data: