version: '3.9'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - user_mgmt
      - mongodb

  user_mgmt:
    build: ./user_mgmt
    ports:
      - "5005:5005"
    environment:
      MONGO_URI: mongodb://mongodb:27017/NEUROCON
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
