version: '3.9'

services:
  user_mgmt:
    build: ./user_mgmt
    ports:
      - "5005:5005"
    environment:
      MONGO_URI: mongodb://mongodb:27017/NEUROCON
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005"] # Check if the Flask server is responding
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: